name: StopWatch
version: 0.3.7
author: DevGang
main: stopwatch.terramc.us.Main

commands:
  playtime:
    description: Displays playtime
    usage: /playtime
  stopwatch:
    description: Displays the time remaining on your timer.
    usage: /stopwatch
  stopwatch menu:
    description: Displays a more detailed help menu.
    usage: /stopwatch menu
  stopwatch mode:
    description: Switches between the various modes available, or displays a help menu if no argument is provided.
    usage: /stopwatch mode [alarm/timer]
  stopwatch start:
    description: Begins a timer.
    usage: /stopwatch start hh:mm:ss
  stopwatch stop:
    description: Stops your currently running timer.
    usage: /stopwatch stop
